### ISSUE TITLE
Out of memory when running spring tests

### ISSUE THREAD

**Issue by lucimihai** [andylke/im-aop-loggers#1]
Hello.

I've tried last version of im-aop-loggers on a Java17, SpringBoot 2.6.0 version project and during the spring boot tests I got out of memory.

**Comment by bukajsytlos** [comment]
stacktrace or didn't happen 😀

**Comment by andylke** [comment]
> 



> Hello.
> 
> I've tried last version of im-aop-loggers on a Java17, SpringBoot 2.6.0 version project and during the spring boot tests I got out of memory.

Hi @lucimihai , could you share the code of your tests?

**Comment by lucimihai** [comment]
I did some additional investigations. The memory issue is not related to im-aop-loggers lib. I developed custom aspects and the memory still occurred. So I think is more related to AspectJ or Spring AOP.
I managed to solve it by configuring Xmx=1GB for spring boot integration tests. 
So I'm closing the issue.
