### ISSUE TITLE
Update for Spring 3.x

### ISSUE THREAD

**Issue by el8ted** [andylke/im-aop-loggers#2]
Creating to track a PR.
Spring 3.x has dropped support for /META-INF/spring.factories and jumps to Java 17 (javax -> jakarta). I found the current project did not work without making the change of the AutoConfigured class to @AutoConfigured and creating META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

**Comment by andylke** [comment]
Hi @el8ted new version 1.1.0 released that slis compatible with Spring Boot 3.x.
